### ISSUE TITLE
Correct reading different resolutions.

### ISSUE THREAD

**Issue by eddienko** [TristanWhitmarsh/napari-stpt#4]
The code assumes that different resolutions are stored in groups called "l.2", "l.4", etc.....

This is not really correct and subject to change. The correct way is reading the multiscale attribute in the metadata that tells you where the different groups for the different resolutions are stored:

```
arr.attrs["multiscale"] = {
            "datasets": [
                {"path": "", "level": 1},
                {"path": "l.2", "level": 2},
                {"path": "l.4", "level": 4},
                {"path": "l.8", "level": 8},
                {"path": "l.16", "level": 16},
                {"path": "l.32", "level": 32},
            ],
            "metadata": {"method": "cv2.pyrDown", "version": cv2.__version__},
        }
```

So level 2 is in group "l.2". The name "l.2" can change but this is how you find where they are and how many resolutions are stored in the file

**Comment by TristanWhitmarsh** [comment]
The resolutions are now read and made selectable in the dropdown list when the image is selected.
